# Generated by Django 5.0.2 on 2024-02-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
